flags: {}
extra-package-dbs: []
local-bin-path: /srv/blog/.local/bin
packages:
- '.'
extra-deps:
- Cabal-1.24.0.0
- HTTP-4000.3.3
- HUnit-1.3.1.1
- JuicyPixels-3.2.7
- MonadCatchIO-transformers-0.3.1.3
- MonadRandom-0.4.2.3
- SHA-1.6.4.2
- StateVar-1.1.0.4
- adjunctions-4.3
- aeson-0.11.1.4
- asn1-encoding-0.9.3
- asn1-parse-0.9.4
- asn1-types-0.3.2
- async-2.1.0
- attoparsec-0.13.0.2
- attoparsec-enumerator-0.3.4
- auto-update-0.1.4
- base-orphans-0.5.4
- base64-bytestring-1.0.0.1
- bifunctors-5.3
- blaze-builder-0.4.0.2
- blaze-builder-enumerator-0.2.1.0
- blaze-html-0.8.1.1
- blaze-markup-0.7.0.3
- byteable-0.1.1
- bytestring-builder-0.10.6.0.0
- bytestring-mmap-0.2.2
- case-insensitive-1.2.0.6
- cereal-0.5.1.0
- cipher-aes-0.2.11
- clientsession-0.9.1.1
- cmark-0.5.2
- comonad-4.2.7.2
- conduit-1.2.6.4
- conduit-extra-1.1.13.1
- configurator-0.3.0.0
- connection-0.2.5
- contravariant-1.4
- cookie-0.4.2
- cprng-aes-0.6.1
- crypto-api-0.13.2
- crypto-cipher-types-0.0.9
- crypto-random-0.0.9
- cryptohash-0.11.9
- cryptonite-0.15
- data-default-0.6.0
- data-default-class-0.0.1
- data-default-instances-base-0.1.0
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- digest-0.0.1.2
- directory-tree-0.12.0
- distributive-0.5.0.2
- dlist-0.7.1.2
- easy-file-0.2.1
- either-4.4.1
- enclosed-exceptions-1.0.1.1
- entropy-0.3.7
- enumerator-0.4.20
- exceptions-0.8.2.1
- extensible-exceptions-0.1.1.4
- fail-4.9.0.0
- fast-logger-2.4.6
- filemanip-0.3.6.3
- free-4.12.4
- groundhog-0.7.0.3
- groundhog-postgresql-0.7.0.2
- groundhog-th-0.7.0.1
- haddock-library-1.2.1
- hashable-1.2.4.0
- heist-0.14.1.4
- highlighting-kate-0.6.2
- hourglass-0.2.10
- hslua-0.4.1
- http-client-0.4.28
- http-client-tls-0.2.4
- http-types-0.9
- kan-extensions-4.2.3
- lens-4.12.3
- lifted-base-0.2.3.6
- logict-0.6.0.2
- map-syntax-0.2
- memory-0.12
- mime-types-0.1.0.7
- mmorph-1.0.6
- monad-control-1.0.1.0
- monad-logger-0.3.18
- monad-loops-0.4.3
- monads-tf-0.1.0.2
- mtl-2.2.1
- mwc-random-0.13.4.0
- network-2.6.2.1
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- pandoc-1.17.0.3
- pandoc-types-1.16.1
- parallel-3.2.1.0
- parsec-3.1.9
- pem-0.2.2
- postgresql-libpq-0.9.1.1
- postgresql-simple-0.5.1.2
- prelude-extras-0.4.0.3
- primitive-0.6.1.0
- profunctors-5.2
- pwstore-fast-2.4.4
- random-1.1
- reflection-2
- regex-base-0.93.2
- regex-pcre-builtin-0.94.4.8.8.35
- regex-posix-0.95.2
- resource-pool-0.2.3.2
- resource-pool-catchio-0.2.1.0
- resourcet-1.1.7.3
- scientific-0.3.4.6
- securemem-0.1.9
- semigroupoids-5.0.1
- semigroups-0.18.1
- setenv-0.1.1.3
- skein-1.0.9.4
- snap-0.14.0.7
- snap-core-0.9.8.0
- snap-loader-static-0.9.0.2
- snap-server-0.9.5.1
- snaplet-postgresql-simple-0.6.0.4
- socks-0.5.4
- stm-2.4.4.1
- stm-chans-3.0.0.4
- streaming-commons-0.1.15.4
- syb-0.6
- tagged-0.8.4
- tagsoup-0.13.9
- temporary-1.2.0.4
- texmath-0.8.6.2
- text-1.2.2.1
- tls-1.3.5
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unix-compat-0.4.1.4
- unix-time-0.3.6
- unordered-containers-0.2.7.0
- utf8-string-1.0.1.1
- uuid-types-1.0.3
- vector-0.11.0.0
- vector-algorithms-0.7.0.1
- void-0.7.1
- x509-1.6.3
- x509-store-1.6.1
- x509-system-1.6.3
- x509-validation-1.6.3
- xml-1.3.14
- xmlhtml-0.2.3.4
- yaml-0.8.17.1
- zip-archive-0.3.0.2
- zlib-0.6.1.1
- zlib-bindings-0.1.1.5
- zlib-enum-0.2.3.1
resolver: ghc-7.10.3
